### ISSUE TITLE
[1.8+] Satellite Controllers not working with multiple satellites

### ISSUE THREAD

**Issue by EmosewaPixel** [MJRLegends/Planet-Progression#8]
### Description of Issue
 Satellite Controllers seem to not be researching anything, or at least their GUI says so.

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/25333164/36391170-a5790a64-15a5-11e8-8bd8-113d03f434f8.png)
![image](https://user-images.githubusercontent.com/25333164/36391174-a8ddd180-15a5-11e8-9d32-211dc4cf1bf6.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.2

**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
Your missing a battery/power

**Comment by EmosewaPixel** [comment]
It does have power, the yellow bar is full

**Comment by MJRLegends** [comment]
So it does, replacing the machine or reloading your world should solve it

**Comment by EmosewaPixel** [comment]
Nope, neither of them worked.

**Comment by MJRLegends** [comment]
please send me a copy of your logs, and playerdata file

**Comment by EmosewaPixel** [comment]
Let me just test a few more things first.

**Comment by MJRLegends** [comment]
It should only be showing "Nothing!" when it cant find a research paper left that the player has already unlocked all planets and moons

**Comment by MJRLegends** [comment]
Do you have any other Galacticraft addons installed?

**Comment by EmosewaPixel** [comment]
Ok, tried setting off a satellite in a new world and I got the same I had in the other world:
![image](https://user-images.githubusercontent.com/25333164/36391686-d65ca9b8-15a7-11e8-9858-b8de2a44a59a.png)
![image](https://user-images.githubusercontent.com/25333164/36391714-facac578-15a7-11e8-8df4-12d2ec479984.png)
 And I do have Extra Planets, yet this didn't happen in version 1.0.

**Comment by MJRLegends** [comment]
please send me a copy of your logs, and playerdata file

**Comment by MJRLegends** [comment]
also a copy of your Planet Progression config file :D

**Comment by MJRLegends** [comment]
I think i know the issue, im able to reproduce it.

**Comment by MJRLegends** [comment]
Seems to be a issue with more than one satellite at a time

**Comment by EmosewaPixel** [comment]
-_- I was in the middle of uploading everything, but at least you found i

**Comment by MJRLegends** [comment]
Fix will be out soon, as im working on some features like commands for adding satellites and that for server owners and testing and me purposes :D

**Comment by EmosewaPixel** [comment]
Well, nothing is being approved right now anyways, so I just hope it's released in the next 3h. (as I've been waiting for you for 2 days to update my pack)

**Comment by MJRLegends** [comment]
yeah im still working on it :D it will be within 3 hours yeah

**Comment by MJRLegends** [comment]
Ok i've fixed this bug :D

**Comment by MJRLegends** [comment]
Versions are rolling out with this fixed :D

**Comment by midorlo** [comment]
Still present for me on Modern Skyblock 3, running Planet Progression 0.1.8 on GC 4.0.1.144 and ExtraPlanets 0.2.6

**Comment by MJRLegends** [comment]
Please open a new issue with details like images or videos and fully instructions to what you tried also please test in a new world with new machines and new satellites
